name: ARCHE-Metadata-Import

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Ingest Metadata into ARCHE
    runs-on: ubuntu-latest
    env:
      ARCHE_USER: pandorfer
      ARCHE_PASSWORD: ${{secrets.ARCHE_PASSWORD}}
      ARCHE: https://arche-dev.acdh-dev.oeaw.ac.at/api
      TOPCOLID: https://id.acdh.oeaw.ac.at/emt

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: create metadata
      run: python make_arche_rdf.py
    - name: run metadata import
      run: ./arche__ingest_md.sh
    
        